#!/usr/bin/env python3
"""
Plot sequencing-run summary metrics for subsampling experiments.

Inputs:
    - Clean TSV generated by sequencing_run_summary_stats.sh

Outputs:
  - Line and bar plots under --outdir
  - Aggregated CSV tables under --data-dir
"""
# imports
import argparse
import gzip
import os
import re
import sys
from typing import Dict, List, Sequence, Tuple

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.colors import to_hex, to_rgb
import pandas as pd
import seaborn as sns

##### CSV INGESTION AND DATAFRAME SETUP
# Add the current script directory to the Python path to allow local imports.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from plot_summary_stats import DEFAULT_TYPE_COLOR_MAP, build_assembler_color_map  # noqa: E402


ASSEMBLER_LABEL_ALIASES = {
    "flye": "Flye",
    "metamdbg": "metaMDBG",
    "metaspades_hybrid": "metaSPAdes Hybrid",
    "opera_ms": "Opera-MS",
}


def _valid_hex(color: str) -> bool:
    return bool(re.fullmatch(r"#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})", color.strip()))


def _parse_hex_list(raw: str, label: str) -> List[str]:
    colors = [c.strip() for c in raw.split(",") if c.strip()]
    if not colors:
        raise ValueError(f"{label} palette is empty.")
    invalid = [c for c in colors if not _valid_hex(c)]
    if invalid:
        raise ValueError(
            f"Invalid hex color(s) for {label}: {', '.join(invalid)}. Use #RGB or #RRGGBB."
        )
    return colors

# Helper functions for plotting and data processing.
def _blend_with_white(color: str, amount: float) -> str:
    amount = max(0.0, min(1.0, float(amount)))
    r, g, b = to_rgb(color)
    rb = r + (1.0 - r) * amount
    gb = g + (1.0 - g) * amount
    bb = b + (1.0 - b) * amount
    return to_hex((rb, gb, bb))

# Argument parsing and main entry point. Data directories and file paths are handled here. Inputs from sequencing_run_summary_stats.sh
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot subsampling sequencing-run summary metrics")
    parser.add_argument(
        "--input-tsv",
        default="sequencing_run_summary_stats_log_clean.tsv",
        help="Clean TSV from sequencing_run_summary_stats.sh",
    )
    parser.add_argument(
        "--outdir",
        default="subsampling/plots/sequencing_runs",
        help="Directory for plots",
    )
    parser.add_argument(
        "--data-dir",
        default="subsampling/data",
        help="Directory for aggregated data CSV files",
    )
    parser.add_argument(
        "--subsample-assembly-log",
        default="subsample_assembly_summary_stats_log.txt",
        help="Assembly stats log for subsamples (used for cumulative contig plot)",
    )
    parser.add_argument(
        "--true-assembly-log",
        default="summary_stats_log.txt",
        help="Assembly stats log with true assemblies (used for cumulative contig plot)",
    )
    parser.add_argument(
        "--max-tsv-points-per-curve",
        type=int,
        default=5000,
        help="Maximum points written per cumulative curve TSV series (0 writes all points)",
    )
    parser.add_argument(
        "--long-colors",
        default=",".join(DEFAULT_TYPE_COLOR_MAP["long_read"]),
        help="Comma-separated hex colors for long_read assemblers.",
    )
    parser.add_argument(
        "--short-colors",
        default=",".join(DEFAULT_TYPE_COLOR_MAP["short_read"]),
        help="Comma-separated hex colors for short_read assemblers.",
    )
    parser.add_argument(
        "--hybrid-colors",
        default=",".join(DEFAULT_TYPE_COLOR_MAP["hybrid_read"]),
        help="Comma-separated hex colors for hybrid_read assemblers.",
    )
    return parser.parse_args()

# File handling and summary block parsing functions.
def _open_text_maybe_gzip(path: str):
    if path.lower().endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8", errors="replace")
    return open(path, "r", encoding="utf-8", errors="replace")


def _split_summary_blocks(log_path: str) -> List[str]:
    if not os.path.isfile(log_path):
        return []

    with open(log_path, "r", encoding="utf-8") as handle:
        lines = handle.readlines()

    blocks: List[str] = []
    current: List[str] = []
    for line in lines:
        if line.startswith("Timestamp:"):
            if current:
                blocks.append("".join(current))
                current = []
            current.append(line)
            continue

        if line.startswith("Assembly:") and not current:
            current.append(line)
            continue

        if current:
            current.append(line)

    if current:
        blocks.append("".join(current))
    return blocks


def _parse_block_meta(block: str) -> Dict[str, str]:
    sample = ""
    assembler = ""
    assembly_path = ""

    for line in block.splitlines():
        if line.startswith("Sample:"):
            sample = line.split("Sample:", 1)[1].strip()
        elif line.startswith("Assembler:"):
            assembler = line.split("Assembler:", 1)[1].strip()
        elif line.startswith("Assembly:"):
            assembly_path = line.split("Assembly:", 1)[1].strip()

    return {"sample": sample, "assembler": assembler, "assembly_path": assembly_path}


# Curve specification and downsampling functions. Counts contigs of length above a minimum threshold from FASTA files.
def _contig_lengths_from_fasta(path: str, min_length_bp: int = 1000) -> List[int]:
    lengths: List[int] = []
    current = 0

    with _open_text_maybe_gzip(path) as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(">"):
                if current >= min_length_bp:
                    lengths.append(current)
                current = 0
                continue
            current += len(line)

    if current >= min_length_bp:
        lengths.append(current)
    return lengths

# 
def _curve_specs() -> List[Dict[str, str]]:
    def _subsample_percent_label(level: int) -> str:
        # Use truncation (not rounding) so labels follow 1/12, 2/12 style expectations (8.3, 16.6, ...).
        tenths = (level * 1000) // 12
        return f"{tenths / 10.0:.1f}%"

    return [
        {"label": "100.0% (true)", "sample": "S1", "log_kind": "true", "fraction": "1.0"},
        *[
            {
                "label": _subsample_percent_label(idx),
                "sample": f"S1_subsample_{idx}",
                "log_kind": "subsample",
                "fraction": f"{idx / 12.0:.6f}",
            }
            for idx in range(1, 12)
        ],
    ]

# Downsample cumulative contig curves to a maximum number of points for plotting.
def _downsample_curve(
    contig_count: Sequence[int],
    cumulative_mbp: Sequence[float],
    max_points_per_curve: int,
) -> Tuple[List[int], List[float]]:
    if max_points_per_curve <= 0 or len(contig_count) <= max_points_per_curve:
        return list(contig_count), list(cumulative_mbp)

    n = len(contig_count)
    step = max(1, (n - 1) // (max_points_per_curve - 1))
    idxs = list(range(0, n, step))
    if idxs[-1] != n - 1:
        idxs.append(n - 1)

    return [contig_count[i] for i in idxs], [cumulative_mbp[i] for i in idxs]

# Parse curve rows from assembly summary logs for the specified samples.
def _parse_curve_rows(log_path: str, wanted_samples: Sequence[str]) -> Dict[Tuple[str, str], Dict[str, object]]:
    rows: Dict[Tuple[str, str], Dict[str, object]] = {}
    wanted = set(wanted_samples)

    for block in _split_summary_blocks(log_path):
        meta = _parse_block_meta(block)
        sample = meta.get("sample", "")
        assembler = meta.get("assembler", "")
        assembly_path = meta.get("assembly_path", "")

        if sample not in wanted:
            continue
        if not assembler or not assembly_path or not os.path.isfile(assembly_path):
            continue

        lengths = sorted(_contig_lengths_from_fasta(assembly_path), reverse=True)
        if not lengths:
            continue

        cumulative_mbp: List[float] = []
        running = 0
        for length in lengths:
            running += length
            cumulative_mbp.append(running / 1_000_000.0)

        rows[(sample, assembler)] = {
            "sample": sample,
            "assembler": assembler,
            "contig_count": list(range(1, len(lengths) + 1)),
            "cumulative_mbp": cumulative_mbp,
        }

    return rows

# Functions for parsing curve rows and writing cumulative curve TSV files. Sets dataframe records and outputs TSV for plotting.
def _write_cumulative_curve_tsv(
    rows: Dict[Tuple[str, str], Dict[str, object]],
    specs: Sequence[Dict[str, str]],
    data_dir: str,
    max_points_per_curve: int,
) -> str:
    os.makedirs(data_dir, exist_ok=True)
    label_map = {spec["sample"]: spec["label"] for spec in specs}

    records: List[Dict[str, object]] = []
    for (sample, assembler), row in rows.items():
        label = label_map.get(sample, sample)
        contig_count = row.get("contig_count", [])
        cumulative_mbp = row.get("cumulative_mbp", [])
        sampled_count, sampled_cumulative = _downsample_curve(
            contig_count=contig_count,
            cumulative_mbp=cumulative_mbp,
            max_points_per_curve=max_points_per_curve,
        )
        for cidx, cum in zip(sampled_count, sampled_cumulative):
            records.append(
                {
                    "sample": sample,
                    "label": label,
                    "assembler": assembler,
                    "contig_count": cidx,
                    "cumulative_contig_length_mb": cum,
                }
            )

    df = pd.DataFrame(records)
    outpath = os.path.join(data_dir, "s1_true_and_subsamples_cumulative_contig_lengths.tsv")
    if df.empty:
        # Keep a header-only file for reproducibility when no curves are available.
        pd.DataFrame(
            columns=[
                "sample",
                "label",
                "assembler",
                "contig_count",
                "cumulative_contig_length_mb",
            ]
        ).to_csv(outpath, sep="\t", index=False)
    else:
        df.to_csv(outpath, sep="\t", index=False)
    return outpath

#### PLOTTING
# Functions for plotting cumulative contig length four-panel figures.
def plot_cumulative_contig_four_panel(
    subsample_log: str,
    true_log: str,
    outdir: str,
    data_dir: str,
    max_tsv_points_per_curve: int,
    color_map_by_type: Dict[str, Sequence[str]],
) -> None:
    specs = _curve_specs()
    true_samples = [s["sample"] for s in specs if s["log_kind"] == "true"]
    subsamples = [s["sample"] for s in specs if s["log_kind"] == "subsample"]

    rows = {}
    rows.update(_parse_curve_rows(true_log, true_samples))
    rows.update(_parse_curve_rows(subsample_log, subsamples))

    tsv_path = _write_cumulative_curve_tsv(rows, specs, data_dir, max_tsv_points_per_curve)
    print(f"Saved TSV: {tsv_path}")

    if not rows:
        print("No cumulative contig data found for S1/subsamples. Skipping four-panel plot.")
        return

    metaspades_ref_mb = None
    metaspades_ref_row = rows.get(("S1", "metaspades"))
    if metaspades_ref_row and metaspades_ref_row.get("cumulative_mbp"):
        metaspades_ref_mb = float(metaspades_ref_row["cumulative_mbp"][-1])

    pane_order = ["flye", "metamdbg", "metaspades_hybrid", "opera_ms"]
    palette_seed = ["idbaud", "megahit", "metaspades", "flye", "metamdbg", "metaspades_hybrid", "opera_ms"]
    assembler_palette = build_assembler_color_map(palette_seed, color_map_by_type=color_map_by_type)
    ordered_specs = sorted(specs, key=lambda s: float(s.get("fraction", "0")), reverse=True)
    fig, axes = plt.subplots(2, 2, figsize=(17, 12))
    axes = axes.flatten()

    for ax, assembler in zip(axes, pane_order):
        plotted = 0
        for spec in ordered_specs:
            key = (spec["sample"], assembler)
            row = rows.get(key)
            if row is None:
                continue

            fraction = float(spec.get("fraction", "0"))

            base_color = assembler_palette.get(assembler, "#4c72b0")
            # Lower subsample fractions are lighter; full fraction is darkest for that assembler hue.
            lighten_amount = 0.92 - (0.87 * max(0.0, min(1.0, fraction)))
            color = _blend_with_white(base_color, lighten_amount)
            lw = 2.6 if fraction >= 0.999 else 1.6

            x_vals = pd.concat(
                [pd.Series([0.0]), pd.Series(row["contig_count"], dtype=float)],
                ignore_index=True,
            )
            y_vals = pd.concat(
                [pd.Series([0.0]), pd.Series(row["cumulative_mbp"], dtype=float)],
                ignore_index=True,
            )

            ax.plot(x_vals, y_vals, label=spec["label"], color=color, linewidth=lw)
            ax.scatter(row["contig_count"], row["cumulative_mbp"], color=color, s=6, zorder=4)
            plotted += 1

        if plotted == 0:
            ax.set_title(f"{assembler} (no data)")
            ax.axis("off")
            continue

        ax.set_title(ASSEMBLER_LABEL_ALIASES.get(assembler, assembler))
        ax.set_xlabel("Contig count (longest to shortest, log scale)")
        ax.set_ylabel("Cumulative Contig Length (Mb, raw)")
        ax.set_xscale("log")
        ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{int(v):,}" if v >= 1 else f"{v:.2g}"))
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f"{v:,.0f} Mb"))

        if metaspades_ref_mb is not None:
            ax.axhline(
                metaspades_ref_mb,
                color=assembler_palette.get("metaspades", "#238B45"),
                linewidth=2,
                linestyle="-",
                label="S1 metaSPAdes total",
            )

        ax.legend(title="Subsample level", fontsize=7, title_fontsize=8, loc="best")

    fig.suptitle("Subsampling Rarefaction for Hybrid and Long Assemblers", y=1.02)
    fig.tight_layout()
    outpath = os.path.join(outdir, "subsample_s1_cumulative_contig_length_four_panel.png")
    fig.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {outpath}")

# Functions for extracting subsample indices and classifying read groups.
def extract_subsample_index(sample_name: str) -> float:
    # Supports both styles:
    # - S1_subsample_1 .. S1_subsample_11
    # - S1 .. S12
    match = re.search(r"_subsample_(\d+)$", str(sample_name))
    if match:
        return float(match.group(1))

    plain = re.match(r"^S(\d+)$", str(sample_name))
    if plain:
        return float(plain.group(1))

    return float("nan")

# Functions for extracting subsample indices and classifying read groups.
def classify_read_group(path: str) -> str:
    lower = os.path.basename(str(path)).lower()
    if "long" in lower:
        return "long"
    if "r1" in lower:
        return "short_r1"
    if "r2" in lower:
        return "short_r2"
    if lower.endswith(".bam"):
        return "bam"
    return "other"


def load_input(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t")
    required = {"sample", "platform", "reads", "total_bases", "total_gbp", "status", "input"}
    missing = required - set(df.columns)
    if missing:
        raise SystemExit(f"Missing required columns: {sorted(missing)}")

    df = df[df["status"] == "ok"].copy()
    df["subsample_idx"] = df["sample"].map(extract_subsample_index)
    df = df.dropna(subset=["subsample_idx"]).copy()
    df["subsample_idx"] = df["subsample_idx"].astype(int)
    df["read_group"] = df["input"].map(classify_read_group)
    return df

# Functions for writing aggregated CSV outputs from the loaded input dataframe.
def write_outputs(df: pd.DataFrame, data_dir: str) -> Tuple[pd.DataFrame, pd.DataFrame]:
    os.makedirs(data_dir, exist_ok=True)

    platform_agg = (
        df.groupby(["sample", "subsample_idx", "platform"], as_index=False)[["reads", "total_bases", "total_gbp"]]
        .sum()
        .sort_values(["subsample_idx", "platform"])
    )

    input_agg = (
        df.groupby(["sample", "subsample_idx", "platform", "read_group"], as_index=False)[
            ["reads", "total_bases", "total_gbp"]
        ]
        .sum()
        .sort_values(["subsample_idx", "platform", "read_group"])
    )

    platform_agg.to_csv(os.path.join(data_dir, "subsample_platform_totals.csv"), index=False)
    input_agg.to_csv(os.path.join(data_dir, "subsample_input_group_totals.csv"), index=False)
    return platform_agg, input_agg

# Functions for applying plot styling and generating summary plots.
def apply_style() -> None:
    sns.set_context("notebook")
    sns.set_style("whitegrid")
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "axes.titlesize": 14,
            "axes.labelsize": 12,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 9,
            "legend.title_fontsize": 10,
        }
    )


def plot_platform_gbp(platform_agg: pd.DataFrame, outdir: str) -> None:
    plt.figure(figsize=(10, 6))
    sns.lineplot(
        data=platform_agg,
        x="subsample_idx",
        y="total_gbp",
        hue="platform",
        marker="o",
        linewidth=2,
    )
    plt.title("Total Sequencing Yield by Subsample")
    plt.xlabel("Subsample Index")
    plt.ylabel("Total Yield (Gbp)")
    plt.xticks(sorted(platform_agg["subsample_idx"].unique()))
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "subsample_yield_gbp_by_platform.png"), dpi=300)
    plt.close()

# Functions for plotting sequencing run summaries.
def plot_ont_reads(platform_agg: pd.DataFrame, outdir: str) -> None:
    ont = platform_agg[platform_agg["platform"].str.lower() == "ont"].copy()
    if ont.empty:
        return

    plt.figure(figsize=(10, 6))
    sns.lineplot(data=ont, x="subsample_idx", y="reads", marker="o", color="#2a9d8f", linewidth=2)
    plt.title("ONT Reads by Subsample")
    plt.xlabel("Subsample Index")
    plt.ylabel("Read Count")
    plt.xticks(sorted(ont["subsample_idx"].unique()))
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "subsample_ont_reads.png"), dpi=300)
    plt.close()


def plot_illumina_r1_r2(input_agg: pd.DataFrame, outdir: str) -> None:
    illumina = input_agg[input_agg["platform"].str.lower() == "illumina"].copy()
    illumina = illumina[illumina["read_group"].isin(["short_r1", "short_r2"])].copy()
    if illumina.empty:
        return

    plt.figure(figsize=(11, 6))
    sns.barplot(data=illumina, x="subsample_idx", y="total_gbp", hue="read_group", errorbar=None)
    plt.title("Illumina Yield by Subsample and Read Pair")
    plt.xlabel("Subsample Index")
    plt.ylabel("Yield (Gbp)")
    plt.tight_layout()
    plt.savefig(os.path.join(outdir, "subsample_illumina_r1_r2_gbp.png"), dpi=300)
    plt.close()

# Main function for orchestrating the loading, processing, and plotting of subsample sequencing runs.
def main() -> None:
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    apply_style()

    try:
        color_map_by_type = {
            "long_read": _parse_hex_list(args.long_colors, "long_read"),
            "short_read": _parse_hex_list(args.short_colors, "short_read"),
            "hybrid_read": _parse_hex_list(args.hybrid_colors, "hybrid_read"),
        }
    except ValueError as exc:
        raise SystemExit(str(exc))

    if os.path.isfile(args.input_tsv):
        df = load_input(args.input_tsv)
        if not df.empty:
            platform_agg, input_agg = write_outputs(df, args.data_dir)
            plot_platform_gbp(platform_agg, args.outdir)
            plot_ont_reads(platform_agg, args.outdir)
            plot_illumina_r1_r2(input_agg, args.outdir)
        else:
            print("Input TSV has no rows with status=ok; skipping sequencing-run summary plots.")
    else:
        print(f"Input TSV not found: {args.input_tsv}; skipping sequencing-run summary plots.")

    plot_cumulative_contig_four_panel(
        subsample_log=args.subsample_assembly_log,
        true_log=args.true_assembly_log,
        outdir=args.outdir,
        data_dir=args.data_dir,
        max_tsv_points_per_curve=args.max_tsv_points_per_curve,
        color_map_by_type=color_map_by_type,
    )

    print(f"Saved plots to: {args.outdir}")
    print(f"Saved data tables to: {args.data_dir}")


if __name__ == "__main__":
    main()
